---
title: 错误处理
description: 通过在React Error Boundary中自动包装管段及其嵌套子级来处理运行时错误。
related:
  links:
    - app/api-reference/file-conventions/error
---

`error.js`文件约定允许您优雅地处理[嵌套路由](/docs/app/building-your-application/routing#nested-routes)中的意外运行时错误.

- 在[React 误差边界](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)中自动包裹管段及其嵌套子级.
- 使用文件系统层次结构来调整粒度，创建针对特定段量身定制的错误 UI。
- 将错误隔离到受影响的段，同时保持应用程序的其余部分正常工作。
- 添加功能，尝试在不重新加载整页的情况下从错误中恢复。

通过在路由段内添加`error.js`文件并导出 React 组件来创建错误 UI：

<Image
  alt="error.js special file"
  srclight="/docs/light/error-special-file.png"
  srcdark="/docs/dark/error-special-file.png"
  width="1600"
  height="606"
/>

```tsx filename="app/dashboard/error.tsx" switcher
"use client"; // Error components must be Client Components

import { useEffect } from "react";

export default function Error({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error);
  }, [error]);

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  );
}
```

```jsx filename="app/dashboard/error.js" switcher
"use client"; // Error components must be Client Components

import { useEffect } from "react";

export default function Error({ error, reset }) {
  useEffect(() => {
    // Log the error to an error reporting service
    console.error(error);
  }, [error]);

  return (
    <div>
      <h2>Something went wrong!</h2>
      <button
        onClick={
          // Attempt to recover by trying to re-render the segment
          () => reset()
        }
      >
        Try again
      </button>
    </div>
  );
}
```

### How `error.js` Works

<Image
  alt="How error.js works"
  srclight="/docs/light/error-overview.png"
  srcdark="/docs/dark/error-overview.png"
  width="1600"
  height="903"
/>

- `error.js`自动创建一个[React 错误边界](https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary)，它**包装**嵌套的子段或`page.js`组件。
- 从`error.js`文件导出的 React 组件用作**fallback**组件。
- 如果在错误边界内抛出错误，则错误被**包含**，回调组件被**呈现**。
- 当回调错误组件处于活动状态时，**错误边界**上方的布局**保持**其状态，**保持**交互，并且错误组件可以显示从错误中恢复的功能。

### 从错误中恢复

错误的原因有时可能是暂时的。在这些情况下，只需再次尝试就可以解决问题。

错误组件可以使用`reset()`函数提示用户尝试从错误中恢复。执行时，该函数将尝试重新呈现`错误`边界的内容。如果成功，则回调错误组件将替换为重新渲染的结果。

```tsx filename="app/dashboard/error.tsx" switcher
"use client";

export default function Error({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button onClick={() => reset()}>Try again</button>
    </div>
  );
}
```

```jsx filename="app/dashboard/error.js" switcher
"use client";

export default function Error({ error, reset }) {
  return (
    <div>
      <h2>Something went wrong!</h2>
      <button onClick={() => reset()}>Try again</button>
    </div>
  );
}
```

### 嵌套路由

通过[特殊文件](/docs/app/building-your-application/routing#file-conventions)创建的 React 组件在[特定嵌套层次结构](/docs/app/building-your-application/routing#component-hierarchy)中呈现.

例如，具有两个段的嵌套路由(均包括`layout.js`和`error.js`文件)在以下*简化*的组件层次结构中呈现：

<Image
  alt="Nested Error Component Hierarchy"
  srclight="/docs/light/nested-error-component-hierarchy.png"
  srcdark="/docs/dark/nested-error-component-hierarchy.png"
  width="1600"
  height="687"
/>

嵌套组件层次结构对`error.js`文件在嵌套路由中的行为有影响：

- 错误冒泡到最近的父错误边界。这意味着`error.js`文件将处理其所有嵌套子段的错误。通过在路由的嵌套文件夹中放置不同级别的`error.js`文件，可以实现或多或少的细粒度错误 UI。
- `error.js`边界**不会**处理**同一**段中的`layout.js`组件中抛出的错误，因为错误边界嵌套在该布局的组件内。

### 处理布局中的错误

`error.js 的边界不会捕获**同一段**的 layout.js 或 template.js 组件中抛出的错误。 当发生错误时，这种[有意层次结构](#nested-routes)使同级路由(如导航)之间共享的重要 UI 保持可见和可用。

要处理特定布局或模板中的错误，请在布局的父段中放置一个`error.js`文件。

要处理根布局或模板中的错误，请使用名为`global-error.js`的`error.js`变体。

### 处理根布局中的错误

根`app/error.js`边界**不会**捕获根`app/layout.js`或`app/template.js`组件中抛出的错误。

要专门处理这些根组件中的错误，请使用位于根`app`目录中的名为`app/global-error.js`的`error.js`变体。

与根`error.js`不同，`global-error.js`错误边界包装**整个**应用程序，其回调组件在活动时替换根布局。因此，需要注意的是，`global-error.js`**必须**定义自己的`<html>`和`<body>`标记。

`global-error.js`是粒度最小的错误 UI，可以被视为整个应用程序的`包罗万象`错误处理。它不太可能经常被触发，因为根组件通常不太动态，其他`error.js`边界将捕获大多数错误。

即使定义了`global-error.js`，仍然建议定义根`error.js`(其回调组件将在**根布局内**呈现)，其中包括全局共享的 UI 和品牌。

```tsx filename="app/global-error.tsx" switcher
"use client";

export default function GlobalError({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  return (
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  );
}
```

```jsx filename="app/global-error.js" switcher
"use client";

export default function GlobalError({ error, reset }) {
  return (
    <html>
      <body>
        <h2>Something went wrong!</h2>
        <button onClick={() => reset()}>Try again</button>
      </body>
    </html>
  );
}
```

### 处理服务器错误

如果在服务器组件内部引发错误，Next.js 将把一个`error`对象(在生产中去掉敏感的错误信息)作为`error`道具转发到最近的`error.js`文件。

#### 保护敏感错误信息

在生产过程中，转发给客户端的`错误`对象只包括通用的`消息`和`摘要`属性。

这是一种安全预防措施，可避免将错误中包含的潜在敏感细节泄露给客户端。

`message`属性包含关于错误的通用消息，`digest`属性包含可用于匹配服务器端日志中相应错误的自动生成的错误哈希。

在开发过程中，转发到客户端的`错误`对象将被序列化，并包括原始错误的`消息`，以便于调试。
